import jsPDF from "jspdf";

export const downloadFraudReport = (alert) => {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();

  // =========================
  // HEADER
  // =========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("INVENTAA", pageWidth / 2, 18, { align: "center" });

  doc.setFontSize(15);
  doc.text("AI Fraud Investigation Report", pageWidth / 2, 28, {
    align: "center",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  doc.text(
    `Generated : ${new Date().toLocaleString()}`,
    pageWidth / 2,
    36,
    { align: "center" }
  );

  doc.setDrawColor(220);
  doc.line(15, 42, 195, 42);

  // =========================
  // Helper
  // =========================

  const card = (x, y, w, h, title) => {
    doc.setDrawColor(210);
    doc.roundedRect(x, y, w, h, 3, 3);

    doc.setFillColor(248, 248, 248);
    doc.roundedRect(x, y, w, 10, 3, 3, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(title, x + 4, y + 7);
  };

  // =========================
  // FRAUD INFO CARD
  // =========================

  card(15, 50, 85, 52, "Fraud Information");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  doc.text("Order ID", 20, 64);
  doc.text(`#${alert.orderId}`, 60, 64);

  doc.text("Risk Score", 20, 74);
  doc.text(`${alert.riskScore}`, 60, 74);

  doc.text("Risk Level", 20, 84);
  doc.text(`${alert.riskLevel}`, 60, 84);

  doc.text("Status", 20, 94);
  doc.text(`${alert.status}`, 60, 94);

  // =========================
  // ORDER INFO CARD
  // =========================

  card(110, 50, 85, 52, "Order Information");

  doc.setFont("helvetica", "normal");
doc.text("Amount", 115, 64);
  doc.text(
  `Rs. ${alert.totalAmount.toLocaleString("en-IN")}`,
  155,
  64
);

  doc.text("Payment", 115, 74);
  doc.text(alert.paymentMethod ?? "--", 155, 74);

  doc.text("Date", 115, 84);
  doc.text(
    alert.createdAt
      ? new Date(alert.createdAt).toLocaleDateString()
      : "--",
    155,
    84
  );

  doc.text("Time", 115, 94);
  doc.text(
    alert.createdAt
      ? new Date(alert.createdAt).toLocaleTimeString()
      : "--",
    155,
    94
  );

  // =========================
  // RULES CARD
  // =========================

  card(15, 112, 180, 38, "Triggered Rules");

  let y = 126;

  doc.setFont("helvetica", "normal");
doc.setFontSize(11);

alert.reason
  ?.split(";")
  .filter(Boolean)
  .forEach((rule) => {
    doc.text(rule.trim(), 20, y+3);
    y += 2;
  });

  // =========================
  // AI ANALYSIS CARD
  // =========================

  card(15, 160, 180, 42, "AI Analysis");

  doc.setFont("helvetica", "normal");

  const analysis =
    `This transaction has been classified as ${alert.riskLevel} risk because multiple fraud indicators were detected. Manual verification is recommended before approving this transaction.`;

  doc.text(analysis, 20, 174, {
    maxWidth: 168,
  });

  // =========================
  // ACTIONS CARD
  // =========================

  card(15, 212, 180, 46, "Recommended Actions");

  const actions = [
    "Review transaction",
    "Verify cashier activity",
    "Review CCTV footage",
    "Monitor future transactions",
  ];

  let actionY = 226;

  actions.forEach((a) => {
    doc.circle(22, actionY - 1, 1.2, "F");
    doc.text(a, 27, actionY);
    actionY += 8;
  });

  // =========================
  // FOOTER
  // =========================

  doc.setDrawColor(220);
  doc.line(15, 275, 195, 275);

  doc.setFontSize(9);

  doc.text(
    "Generated by Inventaa AI Fraud Engine",
    15,
    282
  );

  doc.text(
    "Digitally Generated Investigation Report",
    195,
    282,
    { align: "right" }
  );

  doc.save(`Fraud_Report_${alert.orderId}.pdf`);
};